#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidGrabber.Resource", IsApplication=true)]

namespace AndroidGrabber
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int awaitbtn = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int clearbtn = 2131034114;
			
			// aapt resource value: 0x7f05000f
			public const int evaluatebtn = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int latestzpbtn = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int openchkbx = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int pastebtn = 2131034116;
			
			// aapt resource value: 0x7f050013
			public const int progbar = 2131034131;
			
			// aapt resource value: 0x7f050009
			public const int radioGroup1 = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int radioGroup2 = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int res360pchc = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int res480pchc = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int savechkbx = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int statustxt = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int tableLayout1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int tableRow1 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int typeMP4chc = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int typeWebMchc = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int urlbox = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int zptitlebtn = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
